'use client';

import { useRouter } from 'next/navigation';
import styles from './page.module.css';

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.landing}>
      {/* Ambient Background */}
      <div className={styles.ambientBg} aria-hidden="true">
        <div className={styles.orb1} />
        <div className={styles.orb2} />
        <div className={styles.orb3} />
      </div>

      {/* Navigation */}
      <nav className={styles.nav} role="navigation" aria-label="Main navigation">
        <div className={styles.navContent}>
          <div className={styles.logo}>
            <div className={styles.logoIcon} aria-hidden="true">
              <svg width="32" height="32" viewBox="0 0 32 32" fill="none">
                <rect width="32" height="32" rx="8" fill="url(#logo-grad)" />
                <path
                  d="M10 16L14 20L22 12"
                  stroke="white"
                  strokeWidth="2.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <defs>
                  <linearGradient id="logo-grad" x1="0" y1="0" x2="32" y2="32">
                    <stop stopColor="#818cf8" />
                    <stop offset="1" stopColor="#c084fc" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <span className={styles.logoText}>InterviewPrepAI</span>
          </div>
          <div className={styles.navActions}>
            <button
              className="btn btn-ghost"
              onClick={() => router.push('/interview/join')}
              aria-label="Join an interview as a candidate"
            >
              Join Interview
            </button>
            <button
              className="btn btn-primary"
              onClick={() => router.push('/admin/login')}
              aria-label="Sign in as an admin interviewer"
            >
              Admin Login
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className={styles.hero} aria-label="Hero">
        <div className={styles.heroContent}>
          <div className={styles.heroBadge}>
            <span className={styles.heroBadgeDot} aria-hidden="true" />
            AI-Powered • Open Source • Free
          </div>
          <h1 className={styles.heroTitle}>
            Ace Your Next
            <br />
            <span className="text-gradient">Technical Interview</span>
          </h1>
          <p className={styles.heroSubtitle}>
            An intelligent interview platform with AI-generated questions,
            real-time code execution, adaptive difficulty, and comprehensive
            evaluation. Built for developers, by developers.
          </p>
          <div className={styles.heroActions}>
            <button
              className="btn btn-primary btn-lg"
              onClick={() => router.push('/admin/login')}
              aria-label="Get started as an interviewer"
            >
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                <path d="M10 4V16M4 10H16" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
              </svg>
              Create Interview
            </button>
            <button
              className="btn btn-secondary btn-lg"
              onClick={() => router.push('/interview/join')}
              aria-label="Join an existing interview session"
            >
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                <path
                  d="M8 4H5C4.44772 4 4 4.44772 4 5V15C4 15.5523 4.44772 16 5 16H15C15.5523 16 16 15.5523 16 15V12M12 4H16V8M16 4L9 11"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
              Join Interview
            </button>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className={styles.features} aria-label="Features">
        <div className="container">
          <h2 className={`heading-lg ${styles.sectionTitle}`}>
            Everything You Need for
            <span className="text-gradient"> Technical Interviews</span>
          </h2>
          <div className={styles.featureGrid}>
            {[
              {
                icon: '🤖',
                title: 'AI Question Generation',
                desc: 'Dynamic questions generated by AI based on topic, difficulty, and language preference.',
              },
              {
                icon: '💻',
                title: 'Monaco Code Editor',
                desc: 'Full-featured code editor with IntelliSense, syntax highlighting, and multi-language support.',
              },
              {
                icon: '⚡',
                title: 'Real-time Code Execution',
                desc: 'Run code instantly with self-hosted Judge0 engine. Test against multiple test cases.',
              },
              {
                icon: '🧠',
                title: 'Adaptive Difficulty',
                desc: 'AI adjusts question difficulty based on your performance in real-time.',
              },
              {
                icon: '🛡️',
                title: 'Smart Proctoring',
                desc: 'Tab switch detection, face monitoring, and activity logging for integrity.',
              },
              {
                icon: '📊',
                title: 'Rich Analytics',
                desc: 'Detailed performance breakdowns, topic-wise scoring, and AI-generated feedback.',
              },
            ].map((feature, i) => (
              <article key={i} className={styles.featureCard}>
                <div className={styles.featureIcon} aria-hidden="true">
                  {feature.icon}
                </div>
                <h3 className={styles.featureTitle}>{feature.title}</h3>
                <p className={styles.featureDesc}>{feature.desc}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className={styles.footer} role="contentinfo">
        <div className="container">
          <p className="text-muted text-sm">
            © 2026 InterviewPrepAI. Open Source &amp; Free.
            All AI processing runs locally via Ollama.
          </p>
        </div>
      </footer>
    </div>
  );
}
